import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import SideNav from '@/components/SideNav/SideNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Crypto Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <div className='flex flex-col'>
          <Navbar />
          <main className='flex-grow p-4'>
            {children}
          </main>
          <aside className='lg:flex lg:order-first'>
            <SideNav />
          </aside>
        </div>
      </body>
    </html>
  )
}
